### ISSUE TITLE
Rank-Hot Encoder

### ISSUE THREAD

**Issue by janmotl** [scikit-learn-contrib/category_encoders#199]
Implement Rank-Hot Encoder for ordinal features as described at https://scottclowe.com/2016-03-05-rank-hot-encoder/

**Comment by janmotl** [comment]
Example: https://github.com/kmedian/thermoencoder

**Comment by Rishoban** [comment]
Hi, Can i work on this enhancement??

**Comment by janmotl** [comment]
Go ahead.

**Comment by PaulWestenthanner** [comment]
added in #222
