### ISSUE TITLE
Helmert Encoding generating additional columns

### ISSUE THREAD

**Issue by alexjwang** [scikit-learn-contrib/category_encoders#201]
In [this guide](https://www.kaggle.com/discdiver/category-encoders-examples/notebook#Contrast-Encoders) for categorical encoding, it has the following example:

```py
import numpy as np
import pandas as pd              # version 0.23.4
import category_encoders as ce   # version 1.2.8

pd.options.display.float_format = '{:.2f}'.format # to make legible

# some new data frame for the contrast encoders
df2 = pd.DataFrame({
    'color':["a", "b", "c", "d"], 
    'outcome':[1, 2,  0, 1]})

# set up X and y
X2 = df2.drop('outcome', axis = 1)
y2 = df2.drop('color', axis = 1)

ce_helmert = ce.HelmertEncoder(cols = ['color'])
ce_helmert.fit_transform(X2, y2)
```

The intended output should be:
```
col_color_0	col_color_1	col_color_2	col_color_3
0	1.00	-1.00	-1.00	-1.00
1	1.00	1.00	-1.00	-1.00
2	1.00	0.00	2.00	-1.00
3	1.00	0.00	0.00	3.00
```

Instead, I'm getting:
```
   intercept  color_0  color_1  color_2  color_3  color_4
0          1    -1.00    -1.00    -1.00    -1.00    -1.00
1          1     1.00    -1.00    -1.00    -1.00    -1.00
2          1     0.00     2.00    -1.00    -1.00    -1.00
3          1     0.00     0.00     3.00    -1.00    -1.00
```

Any explanation as to why this is happening would be greatly appreciated.

I'm noticing strange behavior with SumEncoder as well.

**Comment by janmotl** [comment]
This deserves some inspection. In the mean time, consider using `drop_invariant=True`.

**Comment by alexjwang** [comment]
`drop_invariant=True` doesn't change the output.

**Comment by alexjwang** [comment]
`drop_invariant=True` does not appear to fix the issue.

**Comment by DenisVorotyntsev** [comment]
Helmert Encoding is a regression encoder, similar to OHE. Check [my post](https://towardsdatascience.com/benchmarking-categorical-encoders-9c322bd77ee8) on formulas behind encoders.

**Comment by PaulWestenthanner** [comment]
I just couldn't reproduce the error on category encoders 1.2.8 and pandas 0.23.4 (installed via conda). Also for newer versions I cannot reproduce it.  
That's my whole environment:
```
category-encoders==1.2.8
certifi==2018.8.24
numpy==1.14.2
pandas==0.23.4
patsy==0.5.0
python-dateutil==2.7.3
pytz==2018.5
scikit-learn==0.20.0
scipy==1.1.0
six==1.16.0
statsmodels==0.9.0
```
