### ISSUE TITLE
Transformers for continous data

### ISSUE THREAD

**Issue by mglowacki100** [scikit-learn-contrib/category_encoders#227]
Hi
I know that library is focused on categorical-encoding, but I think there is a value in adding at least `StandardScaler` and `MinMaxScaler`, with such nice interface like we have in `one_hot` for dealing with `NaNs` and to have `get_feature_names`. 
What do you think about it?

**Comment by janmotl** [comment]
@wdm0006 ?

**Comment by wdm0006** [comment]
At first glance I'd say no that probably is out of scope for this library (but seems like a good idea in general). The universe of continuous value transformations is quite large and adding that into scope here would be quite a big addition.

**Comment by mglowacki100** [comment]
Yes, there are a lot of continous transformers, but they are quite similar regarding input/output format at least for scalers. I think the easiest way to implement it is to wrap-up scikit-learn continous transformers. Basically, we need to handle missing/unknown values to use it. Additionally: invariants and feature names. Probably this functionality could be common even for categorical encoders.

**Comment by PaulWestenthanner** [comment]
closing this as I also agree that it would be out of scope
