### ISSUE TITLE
Which encoders require nested CV?

### ISSUE THREAD

**Issue by Anjum48** [scikit-learn-contrib/category_encoders#231]
Hi guys - thanks for a great package. There are a lot of encoders I am unfamiliar with and I'm still working through the references.

For normal target encoding, it's good practice nested CV folds to prevent target leakage. I was trying to figure out which other encoders will require nested CV. Is it safe to assume that when I see

`fit(self, X, y, **kwargs)`

instead of

`fit(self, X, y=None, **kwargs)`

Then the `y` value is used by the encoder and there is potential for target leakage?

Here is a list of encoders where I think the target is used:
- TargetEncoder
- CatBoostEncoder
- James-Stein
- Leave one out
- M-estimate
- Weight of Evidence

**Comment by janmotl** [comment]
The list is correct. I have updated the readme.md to separate supervised methods from the unsupervised methods. Also, beware that LeaveOneOut already performs nested CV. But remainder of the supervised does not perform the nested CV.

You may consider writing and submitting a wrapper for nested CV, just like we already have a wrapper for multi-class problems in `category_encoders/wrapper.py`.

**Comment by Anjum48** [comment]
Thanks for the quick reply! I've not written a wrapper before, but it sounds like a great idea and I'll report back if I can get one to work
