### ISSUE TITLE
Ordinal encoder giving unexpected results for pandas Categorical

### ISSUE THREAD

**Issue by Rcubes** [scikit-learn-contrib/category_encoders#244]
Hi guys, 
I just love categorical encoders, but working on a clustering I had a hard time detecting a bug in my code. 
My data is not shareable, but I prepared a small reproducible example to show:

```python
import category_encoders as ce
import pandas as pd
df = pd.DataFrame({'a':[1,2,3],'b':['a',np.nan,'c']})
df.dtypes
```
you'll notice a is an int64 and b is an object. If I use ordinal encoding
```python
ord = ce.OrdinalEncoder()
ord.fit_transform(df)
```
I get b encoded as expected 1,2,3.

Normally in pandas, I use pd.Categorical for dealing with big datasets with categories.

If using data with pandas Categories:
```python
import category_encoders as ce
import pandas as pd
df = pd.DataFrame({'a':[1,2,3],'b':['a',np.nan,'c']})
df['b'] = pd.Categorical(df.b)

ord = ce.OrdinalEncoder()
ord.fit_transform(df)
```

I get a really weird value -2147483648 as encoding for the NaN

As per documentation:
handle_missing: str
options are ‘error’, ‘return_nan’, and ‘value, default to ‘value’, which treat nan as a category at fit time, or -2 at transform time if nan is not a category during fit.

am I missing something??

I'm using category_encoders 2.1.0 and Python 3.7.4.
Please let me know if you need more info on my end.

Thanks in advance,

Alfonso

**Comment by janmotl** [comment]
Hi Alfonso. When I run it with the Categorical, I am getting:
```
   a  b
0  1  1
1  2  2
2  3  3
```

I guess there is going to be an issue with the interaction between the specific pandas version and category_encoders. I used pandas 1.0.1 and the master branch of category_encoders from git. Can you try to reproduce the error with a different version of pandas than you currently use?  And can you test master branch of category_encoders from git?

**Comment by Rcubes** [comment]
Hi guys, I re-ran the previous example using pandas 1.0.1

With example 1 I get 1,2,3.
With example 2, meaning, transforming into categories, I get 1, -1 and  2

I think this is better, since it is encoding nan as -1,  but i wanted to check as per documentation and the package site is down.

I think encoding np.nan as -1 is reasonable, because if you call df['b'] it says there are only 2 categories, but not sure if that is clearly stated in the docs.

The thing is why when using the dtype as object np.nan is considered a another encoding as 2?
Probably this should be considered an inconsistency.

I will check this issue as per documentation as soon as the site is back.
Would you guys check this out?

Thanks

**Comment by janmotl** [comment]
The documentation page should be working again. The documentation for OrdinalEncoder says:
```
    handle_missing: str
        options are 'error', 'return_nan', and 'value, default to 'value', which treat nan as a category at fit time,
        or -2 at transform time if nan is not a category during fit.
```
Hence, OrdinalEncoder may decide to assign any unique value to np.nan, till np.nan appears in the training data (and till the Categorical feature is not defined as "ordered"). In the new 2.2.2 version of category_encoders, the order is defined by `X[col].unique().tolist()` and you should not be getting negative values like -2147483648 anymore. 

With both, pandas 1.0.1 and 1.0.3, when I execute following code:
```python
        import category_encoders as ce  # version 2.2.2
        import pandas as pd  # version 1.0.1 or 1.0.3
        df = pd.DataFrame({'a': [1, 2, 3], 'b': ['a', 'b', 'c']})
        df['b'] = pd.Categorical(df.b)
        df_nan = pd.DataFrame({'a': [1, 2, 3], 'b': ['a', np.nan, 'c']})
        df_nan['b'] = pd.Categorical(df_nan.b)

        ord = ce.OrdinalEncoder(handle_unknown='value', handle_missing='value')
        print(ord.fit(df_nan).transform(df_nan))
        ord = ce.OrdinalEncoder(handle_unknown='value', handle_missing='value')
        print(ord.fit(df).transform(df_nan))
```
I am getting:
```
   a  b
0  1  1
1  2  2
2  3  3
   a  b
0  1  1
1  2 -2
2  3  3
```
That seems to be in accordance with the documentation.

1. Test the new release of category_encoders. In both versions of pandas, category_encoders should behave in accordance to the documentation.
2. Let me know if the documented behavior causes troubles. Or whether the documentation should be improved (suggestions are welcomed).

**Comment by Rcubes** [comment]
awesome, I noticed the new version, I searched for it in conda-forge and it is not there yet, do you have any ETA or should I use pip?

Thanks,

**Comment by janmotl** [comment]
It commonly takes a few days until it bubbles through.

**Comment by Rcubes** [comment]
Hi Guys, I checked the results with the new version and they are as expected. I'm good to close this issue. Thnaks for your help.
