### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by Galileo-Galilei** [scikit-learn-contrib/category_encoders#250]
Hello, 

the current link to the documentation is broken (http://contrib.scikit-learn.org/category_encoders/). I cannot access directly to a specific page, the whole website seems down. Any plan to fix it soon? 

Many thanks to the team (for the package and fix) !

**Comment by wdm0006** [comment]
Thanks for the heads up, fixed now:

http://contrib.scikit-learn.org/category_encoders/
