### ISSUE TITLE
Some confusions about BinaryEncoder

### ISSUE THREAD

**Issue by AshiakerWang** [scikit-learn-contrib/category_encoders#264]
It seems that there are some **redundant bits** in the output of [BinaryEncoder](http://contrib.scikit-learn.org/category_encoders/binary.html).

For example, in the following code :

```
import pandas as pd
from IPython.core.display import display
from category_encoders import *
from sklearn.datasets import load_boston

bunch = load_boston()
X = pd.DataFrame(bunch.data, columns=bunch.feature_names)
enc = BinaryEncoder(cols=['RAD']).fit(X)
numeric_dataset = enc.transform(X)
display(numeric_dataset.head(1000))  
```
The `RAD_0`  column of the output `numeric_dataset ` contains only zeros:
```
>>>numeric_dataset['RAD_0'].value_counts()
0    506
```
Number of  **log2⌈m⌉ bits**  is sufficient to encode a column which contains m possible categories, isn't it ? 
In the example above,  log2⌈9⌉ bits = 4 is sufficient to encode the `'RAD'` column, where 9 is the number of categories in the `'RAD'` column.
Therefore, I suppose the `RAD_0`  column of the output is redundant.
It will be appreciated if you could give me some suggestions about the rational of introducing such extra column (i.e. `RAD_0`) in the output.

**Comment by kerrickstaley** [comment]
I opened a PR to fix this issue: https://github.com/scikit-learn-contrib/category_encoders/pull/296
