### ISSUE TITLE
WOEEncoder: wrong WOE formula?

### ISSUE THREAD

**Issue by carvalhomb** [scikit-learn-contrib/category_encoders#274]
Hi,
in the WOE formula in the WOEEncoder, isn't it inverted?

The formula of WOE is calculated by taking the natural logarithm (log to base e) of division of % of non-events and % of events (as per https://www.listendata.com/2015/03/weight-of-evidence-woe-and-information.html).

So, in https://github.com/scikit-learn-contrib/category_encoders/blob/a810a4b7abfce9fc4eb7fc401e3d37f2c1c6e402/category_encoders/woe.py#L261, instead of 

```
nominator = (stats['sum'] + self.regularization) / (self._sum + 2*self.regularization)  
denominator = ((stats['count'] - stats['sum']) + self.regularization) / (self._count - self._sum + 2*self.regularization) 
```

shouldn't it be

```
nominator = ( (stats['count'] - stats['sum']) + self.regularization) / ( (self._count - self._sum) + 2*self.regularization)  
denominator = (stats['sum'] + self.regularization) / (self._sum + 2*self.regularization) 
```
?

**Comment by GLevV** [comment]
stats['sum'] is number of 1 (n_event).
stats['count'] - stats['sum'] is number of 0 (n_non_event).

The formula is correct. 

You can even look at the python code in the cited article
`d['WoE'] = np.log(d['% of Events']/d['% of Non-Events'])`

**Comment by carvalhomb** [comment]
Hi, thanks for the reply.

I'm quite confused, because indeed, the Python the code in the cited article matches what you wrote in your code above, but in the text itself, the WOE formula is defined as:

WOE = In(% of non-events ➗ % of events)

![image](https://user-images.githubusercontent.com/11425202/105633029-9bdbbe00-5e56-11eb-852d-7f09d52676cf.png)

I couldn't figure this out yet, because while some articles list the formula with non-events in the nominator (https://towardsdatascience.com/model-or-do-you-mean-weight-of-evidence-woe-and-information-value-iv-331499f6fc2, http://ucanalytics.com/blogs/information-value-and-weight-of-evidencebanking-case/), I did see other articles using the opposite (https://multithreaded.stitchfix.com/blog/2015/08/13/weight-of-evidence/). 

I will investigate a bit more to see if I find a trusted source for the formula and report back.

**Comment by GLevV** [comment]
Mathematically this does not matter. After log transformation the only difference between these two fractions would be the sign. The ranking relationship between encoded variables will be the same in both cases.
Example:
ln(3/6) = -0.693...
ln(6/3) = 0.693..
Of course it's nice to have standardized version of something, but I guess it's not the case in this situation.

**Comment by carvalhomb** [comment]
Oh, I see! Thanks for clarifying. In that case, I'm sorry for the extra work. 
Closing the issue.
Cheers!
