### ISSUE TITLE
Resolve pandas dependecy (FutureWarning)

### ISSUE THREAD

**Issue by deltawi** [scikit-learn-contrib/category_encoders#281]
## Expected Behavior
No warning

## Actual Behavior
Getting a warning related to pandas dependecy : 

`/python3.7/site-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):`

## Steps to Reproduce the Problem

  1. Use the library with the following versions of Sklearn and Pandas:
```
pandas: '1.1.3'
sklearn: '0.23.2'
```

## Specifications

  - Version: python 3.7
  - Platform: lunix Redhat

**Comment by philip-khor** [comment]
#266
