### ISSUE TITLE
TargetEncoder Unresponsive to Smoothing Parameter

### ISSUE THREAD

**Issue by JonathanBechtel** [scikit-learn-contrib/category_encoders#284]
## Expected Behavior
When the smoothing parameter is adjusted the values will either be closer to the prior value (if it's set to 1), or to the average categorical value(if it's set to 0)

## Actual Behavior
Returned categorical values are always the true average value, regardless of the smoothing parameter.  Ie, if you have the categories dog, cat, mouse, and the average y values of each are 12, 24, and 37, respectively, these are always the values returned by the target encoder, regardless of the smoothing parameter.

## Steps to Reproduce the Problem

  1.  Line 174 in target_encoders.py is the main culprit.  It always returns 1, regardless of the value of the smoothing parameter.

## Specifications

  - Version: 2.2.2
  - Platform: Windows 10
  - Subsystem:

**Comment by cmougan** [comment]
@JonathanBechtel  which regularization parameters are you using?
