### ISSUE TITLE
LeaveOneHotEncoder returns wrong output (multiplied class levels) *critical*

### ISSUE THREAD

**Issue by agilebean** [scikit-learn-contrib/category_encoders#289]
This is IMHO a critical error, as it would falsify all research findings conducted with the LeaveOneHotEncoder.

## Expected Behavior

As any other encoder in the category_encoders library, LeaveOneHotEncoder should return a single value as encoding per class level. 
Example:
In current dataset, the feature `job_type` contains 4 class levels.
This feature is encoded by `scikit-Mestimate` into 4 values, namely:
```
1 58.696997132941      5
2 62.1102766263165  4308
3 64.4396724145027    54
4 66.1381150538009    51
```
density plot:
![image](https://user-images.githubusercontent.com/28497542/104289414-736dce80-54fc-11eb-8682-947ce54faa86.png)

plot target vs. feature (encoded by Mestimate):
![image](https://user-images.githubusercontent.com/28497542/104290001-21797880-54fd-11eb-9381-6e018beb110c.png)

## Actual Behavior
`scikit-loo` converts the same  feature `job_type` into 94 values, starting with:
```
[1] 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028
  [12] 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028
...
 [111] 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028
 [122] 64.43967 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028 62.11028
 [133] 64.43967 62.11028 62.11028 62.11028 62.11028 66.13812 62.11028 62.11028 62.11028 62.11028 62.11028
```

density plot:
![image](https://user-images.githubusercontent.com/28497542/104289462-84b6db00-54fc-11eb-9bef-524139d60d33.png)

The density plot reveals that the encoding is NOT concentrated on 4 distinct values but dispersed.
This is even more evident in the following plot.

plot target vs. feature (encoded by LeaveOneOut):
![image](https://user-images.githubusercontent.com/28497542/104290099-453cbe80-54fd-11eb-8d8f-88a178366872.png)

The previous plot clearly shows the problem:
The LeaveOneOut encoder converts the class levels into a distribution, and then performs the encoding on this distribution. This results into the encoding of the target across the whole range of the distribution, effectively encoding the target by a linear relationship.

Proof:
When extracting the numeric difference of prediction between LeaveOneOut and Mestimate by
```
   jobtype.loo jobtype.mestimate groundtruth    delta12
 1        62.1              62.1          36  0.00606  
 2        62.1              62.1          88 -0.00601  
 3        62.1              62.1          78 -0.00369  
 4        62.1              62.1          99 -0.00857  
 5        62.1              62.1          57  0.00119  
 6        62.1              62.1          33  0.00676  
 7        62.1              62.1          70 -0.00183  
 8        62.1              62.1          62  0.0000256
 9        62.1              62.1          36  0.00606  
10        62.1              62.1          78 -0.00369
```
this difference `delta12` shows an almost exact linear relationship with the target around 0:

![image](https://user-images.githubusercontent.com/28497542/104290996-59cd8680-54fe-11eb-8542-a016eec23dfd.png)

## Steps to Reproduce the Problem

The same code `encoder.fit_transform()` was used to perform the category encoding for for LeaveOneOut and all other encoders, using the trainingset and trainingset target.

The problem only ocurred with the LeaveOneOut encoder, as shown in this plot:

![image](https://user-images.githubusercontent.com/28497542/104291563-060f6d00-54ff-11eb-91bb-f9c68d0bee44.png)

## Specifications

  - Version:
 category_encoders 2.2.2

  - Platform:
MacOS Big Sur 11.2
  - Subsystem:

**Comment by PaulWestenthanner** [comment]
Hi @agilebean 
This is actually expected behaviour.  
On the training set the leave one out encoder does not use the current row for calculating the encoding value. This is in order to avoid overfitting for values of categorical attributes with low cardinality. So for regression problems the encoded values should differ greatly. On other data sets (validation, test, new unseen data) the learned mapping is applied (and you only have one value per category).
