### ISSUE TITLE
[BUG] Some encoders return NaN values

### ISSUE THREAD

**Issue by iki77** [scikit-learn-contrib/category_encoders#290]
## Expected Behavior
All encoders should be able to map encoded features back to the X array/DataFrame, as long the X and y have the same number of rows. 

## Actual Behavior
Some encoders, such as LeaveOneOut and CatBoost, will return NaN values if the X and y have a different index although they have the same number of rows, It seems that the models rely too much on index and unable to map back the encoded features back if the indexes are different.

## Steps to Reproduce the Problem

- 1. Train test split X and y
- 2. Save y train as csv without index
- 3. Reload train y, which will result in y train having default index (0, 1, 2, etc)
- 4. Use ColumnTransformer and use CatBoostEncoder / LeaveOneOutEncoder for categorical features in X train 
- 5. Fit transform ColumnTransformer using X train and y train (same number of rows, but different index)
- 6. Encoded categorical features in X train will have NaN values

**Comment by lahdjirayhan** [comment]
I want to add that TargetEncoder sometimes also returns NaN too. However, I'm not yet able to pin down whether the differing index is the culprit.

**Comment by iki77** [comment]
@lahdjirayhan you should try to make the index of the X and y the same, I found this "fix" because of the same problem you have.

**Comment by iki77** [comment]
It is similar, but the X is pandas DataFrame and y is pandas Series

**Comment by PaulWestenthanner** [comment]
This issue is fixed right? The behaviour now is to check both indices and if they don't match and error is thrown.
