### ISSUE TITLE
Add Unary/ Thermometer Encoding

### ISSUE THREAD

**Issue by iki77** [scikit-learn-contrib/category_encoders#299]
Add Unary/Thermometer Encoding as an alternative for Ordinal Encoding.
According to [Source](https://openreview.net/forum?id=S18Su--CW) it is also more robust to adversarial examples

**Comment by GLevV** [comment]
This is an alternative to one hot encoding, not ordinal. But it could be interesting and should be relatively easy to do

**Comment by GLevV** [comment]
I think it could be added as a parameter to existing OHE implementation

**Comment by PaulWestenthanner** [comment]
I've finally worked on this. This issue is a duplicate of #199 anyway right?

**Comment by PaulWestenthanner** [comment]
added in #222
