### ISSUE TITLE
feature suggestion: Add Gray encoding

### ISSUE THREAD

**Issue by sbrugman** [scikit-learn-contrib/category_encoders#300]
## Feature description
> Gray Encoding. Our second approach is a variant of binary encoding, namely, Gray encoding [24].
It is a binary encoding system where two successive values differ in only one bit. See examples in
Figures 2 and 3: the same set of binary identifiers are generated, but in a different order compared to
the sequence of the attribute values. When combined with PrivBayes, it inherits some of the pros
and cons of the natural binary encoding, but potentially brings some advantages. As successive
values share most bits, **Gray encoding can be more robust to noise.** Take the value (30, 40] of
attribute “age” as an example (Figure 2). If the perturbation in PrivBayes happens to change the
first or the last bit of its code 0102, then the noisy code (i.e., 1102 or 0112) will correspond to a
value adjacent to the original one. Thus, the distortion of information is reduced. In contrast, the
natural binary encoding does not have this property. Therefore, Gray encoding is a competitive
alternative to the natural binary encoding.

From https://dl.acm.org/doi/pdf/10.1145/3134428
Reference implementation: https://github.com/sdv-dev/SDGym/blob/70e5010ca0733bda9aa1cf7c579d04228b95930e/privbayes/code/tools.h#L78

**Comment by PaulWestenthanner** [comment]
I've added a PR for this
