### ISSUE TITLE
Raises ValueError instead of NotFittedError like other sklearn transformers

### ISSUE THREAD

**Issue by princyok** [scikit-learn-contrib/category_encoders#301]
## Issue description

Raises ValueError instead of NotFittedError (raised by sklearn transformers) when you run `transform` before fitting.

## Code demonstration 
The code below raises ValueError:
````python
from category_encoders import one_hot
import pandas as pd
data = pd.DataFrame({"a":["aa", "bb", "cc", "aa"])
one_hot.OneHotEncoder().transform(data)
````

The code below raises NotFittedError:
````python
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
data = pd.DataFrame({"a":["aa", "bb", "cc", "aa"])
OneHotEncoder().transform(data)
````
## Specifications

  - Version: 2.2.2
  - OS: Windows 10

**Comment by PaulWestenthanner** [comment]
fixed in #325
