### ISSUE TITLE
scipy.misc not exist factorial

### ISSUE THREAD

**Issue by taishanfuxiao** [scikit-learn-contrib/category_encoders#307]
## Expected Behavior
from scipy.misc import factorial is error non in the "factorial" in scipy 1.5.2

## Actual Behavior
actual from scipy.special  import factorial is right
should repair category-encoders scipy version

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by vinayaksable2399** [comment]
upgrading statsmodels will fix this issue nowadays: ```pip install statsmodels --upgrade```

**Comment by PaulWestenthanner** [comment]
This is not an issue on our side since we do not import `factorial from scipy.misc`
