### ISSUE TITLE
M-Estimate Encoding error

### ISSUE THREAD

**Issue by Mickael01** [scikit-learn-contrib/category_encoders#316]
## Actual Behavior

When running fit on the MEstimateEncoder
a Value error occurs
ValueError: could not convert string to float: 'Crawford'

## Steps to Reproduce the Problem
```
X = df.copy()
y = X.pop('Neighborhood')
Encoding split
X_encode = X.sample(frac=0.10,random_state=0)
y_encode = y[X_encode.index]
# Training split
X_pretrain = df.drop(X_encode.index)
y_train = y[X_pretrain.index]
encoder = MEstimateEncoder(verbose=True,
    cols=["Neighborhood"],
    m=2)
# print(X_encode["SaleType"])

# Fit the encoder on the encoding split
encoder.fit(X_encode, y_encode)

# Encode the training split
X_train = encoder.transform(X_pretrain, y_train)
``` 

## Specifications

  - Version: 2.2.2 of category_encoders
  - Platform: Kaggle platform
  - Subsystem:

**Comment by PaulWestenthanner** [comment]
How does your `df` look like? Could you please give the definition of the `df` variable?

**Comment by PaulWestenthanner** [comment]
Actually the M-Estimate also works for regression problems. I should change this in the documentation. Your error was as you noticed setting y to be the neighborhood instead of the sale price. With the sale price it should work.
