### ISSUE TITLE
[Release]: Docs have methods that are not released yet

### ISSUE THREAD

**Issue by FaradayDetu** [scikit-learn-contrib/category_encoders#323]
```python
import category_encoders as ce

encoder = ce.BackwardDifferenceEncoder(cols=[...])
encoder = ce.BaseNEncoder(cols=[...])
encoder = ce.BinaryEncoder(cols=[...])
encoder = ce.CatBoostEncoder(cols=[...])
encoder = ce.CountEncoder(cols=[...])
encoder = ce.GLMMEncoder(cols=[...])
encoder = ce.HashingEncoder(cols=[...])
encoder = ce.HelmertEncoder(cols=[...])
encoder = ce.JamesSteinEncoder(cols=[...])
encoder = ce.LeaveOneOutEncoder(cols=[...])
encoder = ce.MEstimateEncoder(cols=[...])
encoder = ce.OneHotEncoder(cols=[...])
encoder = ce.OrdinalEncoder(cols=[...])
encoder = ce.SumEncoder(cols=[...])
encoder = ce.PolynomialEncoder(cols=[...])
encoder = ce.TargetEncoder(cols=[...])
encoder = ce.WOEEncoder(cols=[...])
encoder = ce.QuantileEncoder(cols=[...])


AttributeError: module 'category_encoders' has no attribute 'QuantileEncoder'
```

I believe the issue is that there has not been a release since the PR

**Comment by PaulWestenthanner** [comment]
Thanks for pointing this out! Seems like our docs are deployed when code is merged rather than on a new release. @wdm0006 do you have an idea why this is happening?

**Comment by cmougan** [comment]
@PaulWestenthanner  it appears that the build is failing. `FAILED tests/test_encoders.py::TestEncoders::test_drop_invariant - TypeError:...`

Ain't this what we solved?

**Comment by PaulWestenthanner** [comment]
Your link points to an old build. We fixed that. The latest build was successful https://github.com/scikit-learn-contrib/category_encoders/actions/runs/1417834114

**Comment by wdm0006** [comment]
Docs will only build on release now.

**Comment by cmougan** [comment]
@PaulWestenthanner Is there a release planed soon?

**Comment by PaulWestenthanner** [comment]
@wdm0006 is in charge of releases at the moment. But I think it would make sense to have a release soon

**Comment by wdm0006** [comment]
Yeah we can do a release whenever, @PaulWestenthanner if you can update the version tag and changelog at some point and open an issue I can walk you through how to cut releases so I'm not a single point of failure there also.

**Comment by skehoe3** [comment]
Any update on a release plan?

**Comment by PaulWestenthanner** [comment]
A new release was made. I wasn't aware I already had to rights to do so. I'm sorry it took that long.
