### ISSUE TITLE
Target Encoder Giving Nan values

### ISSUE THREAD

**Issue by shauryauppal** [scikit-learn-contrib/category_encoders#340]
## Expected Behavior
Target Encoder giving Nan values for few inputs

Same Issue:
- https://stackoverflow.com/questions/68261917/why-is-target-encoder-encoding-some-values-as-nan
- https://www.kaggle.com/questions-and-answers/204970

  - Version: Latest Pip Install Feb 2022 version
  - Platform: Linux
  - Subsystem: N/A

**Comment by PaulWestenthanner** [comment]
Hi @shauryauppal 
Could you please also provide a dataset or even better a self-contained reproducible (minimal) example? Neither in the stackoverflow nor in  the kaggle post the dataset is mentioned. (except for a reference to the kaggle housing prices competition which I can't seem to find)

**Comment by GLevV** [comment]
Maybe sigmoid function is numerically unstable in some cases, maybe using something like 
`scipy.special.expit(stats['count'] - self.min_samples_leaf) / self.smoothing)`
in here
https://github.com/scikit-learn-contrib/category_encoders/blob/02a20aa96c5f1f234ec89a0f781980622e3b193a/category_encoders/target_encoder.py#L170 
could be beneficial, both in terms of speed and stability. It will introduce dependency on scipy though.

But without minimal reproducible example it's a needle in a haystack.

**Comment by PaulWestenthanner** [comment]
neither `stats["count"]` nor `self.smoothing` should be 0. The former cannot even be 0 while for the second the documentation clearly states `The value must be strictly bigger than 0`. Without a reproducible example by @shauryauppal we cannot do anything here
