### ISSUE TITLE
Unexpected input dimension when encoding new data frame 

### ISSUE THREAD

**Issue by borisRa** [scikit-learn-contrib/category_encoders#357]
## Expected Behavior

Expecting only transformed columns.
My data frame had 380 cols, with ONLY 3 categorical to encode.
When I wanted to encode this 3 cols in another data frame I got  this error :

`ValueError: Unexpected input dimension 300, expected 380`

The question is why ? 

## Actual Behavior
Expecting all columns that were in the original data frame .
`ValueError: Unexpected input dimension 300, expected 380`

## Steps to Reproduce the Problem
`final_df_cat_encoder.transform(final_df )`

## Specifications
  - Version: category_encoders.__version__ -> 2.4.0

**Comment by PaulWestenthanner** [comment]
Hi @borisRa 
please check the discussion in #355 which is basically the same issue.
