### ISSUE TITLE
object has no attribute '_get_tags'

### ISSUE THREAD

**Issue by Timaos123** [scikit-learn-contrib/category_encoders#365]
all the encoders encountered the problem of  "'XXXEncoder' object has no attribute '_get_tags'"

**Comment by PaulWestenthanner** [comment]
Hi @Timaos123 

can you please provide the version of category encoders you are using as well as a reproducible code snippet leading to the issue you describe

**Comment by j-sieger** [comment]
@PaulWestenthanner , @Timaos123 :
I was facing the same issue with category encoders . I was using **ce** version of **2.5.1.post0**.
I have resolved it by upgrading my **scikit-learn** framework version from **0.20.0** to **1.0-1** in my sagemaker container creation code.

**Comment by PaulWestenthanner** [comment]
ah that makes sense! Probably we should just drop support for versions < 1 by how

**Comment by PaulWestenthanner** [comment]
I just added sklearn >= 1.0 to the requirements
