### ISSUE TITLE
FloatingPointError: underflow encountered in exp

### ISSUE THREAD

**Issue by CoteDave** [scikit-learn-contrib/category_encoders#377]
catboost version: 2.5.1
numpy version: 1.23.3

![image](https://user-images.githubusercontent.com/49559881/198093330-221da5ec-39e4-41f4-a59f-3da2e875b1ac.png)

t_encoder= TargetEncoder(min_samples_leaf=20, smoothing=10)
t_encoded = t_encoder.fit_transform(new_xy_test_dummy[[cat_col]].astype(str), new_xy_test_dummy[[target_col]], cols = [cat_col])

No nans...

Same data seems to work with WOE encoder. Encountered the problem only with TargetEncoder:
w_encoder= WOEEncoder()
w_encoded = w_encoder.fit_transform(new_xy_test_dummy[[cat_col]].astype(str), new_xy_test_dummy[[target_col]], cols = [cat_col]) = works!

Any Ideas ?

Thanks !

**Comment by PaulWestenthanner** [comment]
can you please provide some data in order to reproduce this and also format your code as code (for better readability)

**Comment by glevv** [comment]
There is an easy and long awaited fix. I can make a PR
