### ISSUE TITLE
Pandas iteritems deprecation warnings

### ISSUE THREAD

**Issue by jerheff** [scikit-learn-contrib/category_encoders#378]
## Expected Behavior
No noisy warnings from running pipelines containing these transformers.

## Actual Behavior
Frequent warnings due to Pandas 1.5 [deprecation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iteritems.html):
```category_encoders/one_hot.py:145: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.```

## Steps to Reproduce the Problem

  1.  Install pandas 1.5.1 and category_encoders 2.5.1
  1. Use the OneHotEncoder in a pipeline
  1. See the warnings on fit

## Specifications

  - Version: 2.5.1
  - Platform: macOS
  - Subsystem:

**Comment by glevv** [comment]
That's because iterrows are in deprecation cycle. I think PolynomialWrapper also uses it.

Should be an easy and quick fix
