### ISSUE TITLE
Adding owner on pypi

### ISSUE THREAD

**Issue by wdm0006** [scikit-learn-contrib/category_encoders#390]
Hey @PaulWestenthanner, I was just checking in and noticed you weren't an owner on PyPI, since you've been maintaining for quite a while you should be. Let me know your PyPI username and I can make sure you're added.

**Comment by PaulWestenthanner** [comment]
Hi Will, thank you. My username is PaulWestenthanner (https://pypi.org/user/PaulWestenthanner/)

**Comment by wdm0006** [comment]
Should be good to go, thanks
