### ISSUE TITLE
Quadratic time intersection on Pandas categories

### ISSUE THREAD

**Issue by willsthompson** [scikit-learn-contrib/category_encoders#407]
## Expected Behavior

Using Pandas CategoryDType columns with OrdinalEncoder do not incur a performance penalty.

## Actual Behavior

Pandas' internal categories are intersected with your computed categories in quadratic time, here

https://github.com/scikit-learn-contrib/category_encoders/blob/45110027b263363b53da8564b912e7ca6d5546e8/category_encoders/ordinal.py#L230-L232

## Steps to Reproduce the Problem

  1. Create a Series with a large number of categories, e.g.
  ```python
  categories = [f"Cat{i}" for i in range(10000)]
  series = pd.Series(
      categories,
      pd.CategoricalDtype(categories=categories, ordered=True),
  )
  ```
  1. Apply ordinal encoder to the series

## Specifications

  - Version: 2.5.0
  - Platform:
  - Subsystem:
  
  
 ## Proposed fix
 
 This would be a very simple one line change:
 
 ```python
 categories = list(set(categories).intersection(set(X[col].dtype.categories)))
 ```
 
I'd be happy to get a PR together if this looks okay to you

**Comment by PaulWestenthanner** [comment]
Hi @willsthompson
thanks for pointing that out. Please go ahead and create a PR

**Comment by willsthompson** [comment]
Closing re: https://github.com/scikit-learn-contrib/category_encoders/pull/409#issuecomment-1548610903
