### ISSUE TITLE
Equivalent method to sklearn's partial_fit? 

### ISSUE THREAD

**Issue by ImSo3K** [scikit-learn-contrib/category_encoders#411]
I wanted to know if its possible to do an incremental / online learning with the category encoders? I have a CSV file that I read in chunks because of its size + I will probably encounter new features in inference time.
Maybe there is a potential workaround?

**Comment by PaulWestenthanner** [comment]
The encoders do not a partial fit, however most encoders implement strategies for handling new data at predict time. This is done via the `handle_unknown` parameter. There are several options (raising an error, returning None, return some sensible value). Please check the docs for the encoder you want to use
