### ISSUE TITLE
Missing text in documentation

### ISSUE THREAD

**Issue by ScoobyQ** [scikit-learn-contrib/category_encoders#416]
## Expected Behavior
Description of how to set sklearn to also output DataFrames to be shown

## Actual Behavior
Description of how to set sklearn to also output DataFrames is missing 

## Steps to Reproduce the Problem

  1. Navigate https://contrib.scikit-learn.org/category_encoders/#known-issues
  2. End of first paragraph text is missing

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by ScoobyQ** [comment]
Thanks for looking into this. The text is currently still missing but perhaps I am a little too quick to review.

**Comment by PaulWestenthanner** [comment]
Yes, I haven't released a new version yet.
