### ISSUE TITLE
Support Pandas 2.1

### ISSUE THREAD

**Issue by celestinoxp** [scikit-learn-contrib/category_encoders#418]
WARNING:C:\Users\username\anaconda3\lib\site-packages\category_encoders\utils.py:50: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return pd.api.types.is_categorical_dtype(dtype)

Windows x64
Python 3.10
scikit-learn 1.3
pandas 2.1

**Comment by PaulWestenthanner** [comment]
fixed by #419
