### ISSUE TITLE
Pandas' string columns are not recognized

### ISSUE THREAD

**Issue by tvdboom** [scikit-learn-contrib/category_encoders#421]
## Expected Behavior
Category encoders should recognize pandas `string` and `string[pyarrow]` types.

## Actual Behavior
The column isn't recognized as categorical, and the dataframe is returned as is.

## Steps to Reproduce the Problem
```python
import pandas as pd
from category_encoders.target_encoder import TargetEncoder

X = pd.DataFrame([['a'], ['b']], dtype="string")
y = [0, 1]
print(X.dtypes)

print(TargetEncoder().fit_transform(X, y))
```

produces output:

```
0    string[python]
dtype: object

Warning: No categorical columns found. Calling 'transform' will only return input data.

   0
0  a
1  b
```

## Specifications

  - Version: 2.6.2

**Comment by tvdboom** [comment]
alright, I'll make a pr

**Comment by PaulWestenthanner** [comment]
thanks
