### ISSUE TITLE
Combining with set_output can produce errors

### ISSUE THREAD

**Issue by JulienRoussel77** [scikit-learn-contrib/category_encoders#437]
## Expected Behavior
Calling set_output(transformer="pandas") should have no impact on a OneHotEncoder, since the outputs are already dataframes.

## Actual Behavior
The OneHotEncoder develops an inconsistent behavior, producing errors in the case of subsequent fit_transform calls.

## Steps to Reproduce the Problem

```
df = pd.DataFrame({"C1": ["a", "a"], "C2": ["c", "d"]})
ohe = OneHotEncoder().set_output(transform="pandas")
ohe.fit_transform(df.iloc[:1]) # commenting this line avoids the error
ohe.fit_transform(df.iloc[:2]) # this line produces an error
```

ValueError: Length mismatch: Expected axis has 3 elements, new values have 2 elements

## Specifications

pandas : 2.0.1
sklearn : 1.3.2
category_encoders : 2.6.3

**Comment by bmreiniger** [comment]
I see what's happening. In `BaseEncoder.fit`, https://github.com/scikit-learn-contrib/category_encoders/blob/06e46db07ff15c362d7de5ad225bb0bffc245369/category_encoders/utils.py#L323
we set `feature_names_out_` by looking at the encoder's transformed output (L324). But when sklearn is set to produce pandas output, it uses that attribute of available at L323. So it uses the old attribute. I expect just deleting the attribute somewhere earlier in `fit` should fix it. This probably affects all the encoders, too, not just OHE.
