### ISSUE TITLE
Is frequency encoding covered in this?

### ISSUE THREAD

**Issue by sebastiangonsal** [scikit-learn-contrib/category_encoders#71]
Is frequency encoding covered with any of these encoders ?

**Comment by wdm0006** [comment]
Nope, do you have a reference for it?

**Comment by ornelaxh** [comment]
@sebastiangonsal do you mean simply the counts of every category?

**Comment by MatteoFelici** [comment]
If this is still needed, I can work on that.

**Comment by MatteoFelici** [comment]
Isn't this the `CountEncoder`? If so, I suggest closing this issue.
